# Configuración para el deploy en Netlify
# Esto le dice a Netlify cómo construir tu sitio Astro

[build]
  # Comando para construir el sitio
  command = "npm run build"
  
  # Directorio que se publicará (Astro lo genera por defecto)
  publish = "dist"